apiVersion: v1
kind: Pod
metadata:
  name: sidecar-sample
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c"]
      args: ["while true; do echo 'Hello from App' >> /var/log/app.log; sleep 2; done"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log
    
    - name: sidecar
      image: busybox
      command: ["sh", "-c"]
      args: ["tail -f /var/log/app.log"]
      volumeMounts:
        - name: shared-logs
          mountPath: /var/log

  volumes:
    - name: shared-logs
      emptyDir: {}