apiVersion: v1
kind: Pod
metadata:
  name: zomato-pod  
  labels:
    app: zomato #Pod label
spec:
  containers:
    - name: zomato-container
      image: kastrov/zomato #public image
      ports:
        - containerPort: 3000 #configured inside the Dockerfile
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec: 
  type: NodePort
  selector:
    app: zomato #must match pod label
  ports:
    - port: 80 #service port - internal access in the cluster
      targetPort: 3000  #pod / container port
      nodePort: 32000 #this is the port where we use to access the app on browser/externally

