apiVersion: v1
kind: Pod
metadata:
  name: swiggy-pod
  labels: 
    app: swiggy
spec:
  containers:
    - name: swiggy-container
      image: kastrov/swiggy
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 80
      targetPort: 3000