apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc	# Name of the StorageClass (used in PVCs via storageClassName)
provisioner: ebs.csi.aws.com  # CSI driver for EBS  # Ensures volumes are dynamically created in AWS when PVC requests storage
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp3	#AWS EBS volume type (gp3 = General Purpose SSD, newer than gp2)

#Delete means EBS Volume will get deleted automatically when the PVC is deleted