apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc	# Name of the PVC (referenced by Pods to mount storage)
spec:
  accessModes:	#Volume can be mounted as read-write by a single node
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi	# Requesting 5GiB of storage
  storageClassName: ebs-sc		 # Refers to the StorageClass (ebs-sc) we created earlier
