- name: Loops concept
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: installation of packages
      yum: name={{item}} state=present
      with_items:
        - git
        - maven
        - tree
        - httpd