- hosts: all
  tasks:
    - name: install git on RedHat
      yum: name=git state=present
      when: ansible_os_family == "RedHat"

    - name: install git on Ubuntu
      apt: name=git state=present
      when: ansible_os_family == "Debian"
