- name: tags playbook
  hosts: all
  become: yes
  tasks:
    - name: installation of git
      yum: 
        name: git
        state: present
      tags: git
    
    - name: installation of docker
      yum:
        name: docker
        state: present
      tags: docker

    - name: starting docker
      service:
        name: docker
        state: started
      tags: startdocker

    - name: creation of user
      user:
        name: kastro
        state: present
      tags: kastro-user