apiVersion: v1
kind: ReplicationController
metadata:
  name: zomato-rc
spec:
  replicas: 3
  selector: #it is used to identify the pods
    app: zomato-app #label to match with pods
  template: #this is the pod template used to create the pod
    metadata:
      name: zomato-pod
      labels:
        app: zomato-app
    spec:
      containers:
        - name: zomato-container
          image: kastrov/zomato
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: NodePort
  selector:
    app: zomato-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 31000 #30000-32767