apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: zomato-rs
spec:
  replicas: 5
  selector:
    matchLabels:  #this selector helps the RS to identify the pods it should manage
      app: zomato-app
      env: dev
  template: #pod template that RS uses to create the pods
    metadata:
      name: zomato-pod
      labels:
        app: zomato-app
        env: dev
    spec:
      containers:
        - name: zomato-container
          image: kastrov/zomato
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: NodePort
  selector:
    app: zomato-app
    env: dev
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30755